### ISSUE TITLE
Peer code review

### ISSUE THREAD

**Issue by sjdev2212** [algerina/Leaderboard#4]
This is an awesome job! 
Here are some suggestions.
Consider using modules to make your code more readable and scalable.
Try not to leave commented code
https://github.com/algerina/Leaderboard/blob/0b025de653b8681938fa16a4f10c6dfa3d83e102/src/style.css#L70https://github.com/algerina/Leaderboard/blob/0b025de653b8681938fa16a4f10c6dfa3d83e102/src/style.css#L70.

**Comment by algerina** [comment]
Thank you @sj1978 for your feedback, I deleted the commented code and I will consider working with modules.
